#!/bin/bash
set -e

CI_COMMIT_SHA=$GITHUB_SHA
CI_COMMIT_AUTHOR=$GITHUB_PUSHER_NAME
echo "CI_COMMIT_SHA=$CI_COMMIT_SHA" >> $GITHUB_ENV
echo "CI_COMMIT_AUTHOR=$GITHUB_PUSHER_NAME" >> $GITHUB_ENV
if [[ "$GITHUB_REF" == refs/tags/* ]]; then
    CI_COMMIT_TAG=${GITHUB_REF#refs/tags/}
    echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> $GITHUB_ENV
fi
echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
echo "CI_COMMIT_AUTHOR=$GITHUB_PUSHER_NAME"
echo "CI_COMMIT_TAG=$CI_COMMIT_TAG"