name: 'git-envs'
description: 'Extract CI_COMMIT_TAG, CI_COMMIT_AUTHOR, and CI_COMMIT_SHA'
author: 'chang'
# inputs:
#   github_token:
#     description: 'GitHub token'
#     required: true
runs:
  using: 'composite'
  steps:
    - name: Run script to extract commit info
      run: bash $GITHUB_ACTION_PATH/scripts/run.sh
      env:
        GITHUB_PUSHER_NAME: ${{ github.event.pusher.name }}
      shell: bash