name: 'gh-access-key'
description: 'use nb-cicd-bot-pk to request for temp github access key'
author: 'chang'
inputs:
  nb-cicd-bot-pk:
    description: "pk for nb cicd bot app"
    required: true
runs:
  using: 'composite'
  steps:
    - name: write pk.pem to disk
      run: echo "${{ inputs.nb-cicd-bot-pk }}" > nb-cicd-bot-pk.pem
      shell: bash
    - name: Run script to request github access key
      run: bash $GITHUB_ACTION_PATH/scripts/run.sh
      shell: bash
