name: 'gh-access-key'
description: 'use nb-cicd-bot-pk to request for temp github access key'
author: 'chang'
inputs:
  NB_CICD_BOT_PK:
    description: "pk for nb cicd bot app"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run script to request github access key
      run: bash $GITHUB_ACTION_PATH/scripts/run.sh
      shell: bash
