name: gh-access-key-test
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'gh-access-key/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: chown
      run: |
        #!/bin/bash
        sudo chown -R $(whoami) .

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: get access key
      id: get_access_key
      uses: nextbillion-ai/actions/gh-access-key@master
      with:
        nb-cicd-bot-pk: ${{ secrets.NB_CICD_BOT_PK }}

    - name: echo
      run: |
        #!/bin/bash
        set -e
        echo -------direct----------
        echo "GH_ACCESS_KEY: $GH_ACCESS_KEY"
        if curl -H "Authorization: Bearer ${GH_ACCESS_KEY}" -H "Accept: application/vnd.github.v3+json"  https://api.github.com/repos/nextbillion-ai/tokamak | grep "Bad credentials" ; then
          echo "invalid access token"
          exit 1
        else
          echo "access token is working"
        fi
  container-test:
    runs-on: self-hosted
    container:
      image: ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: get access key
      id: get_access_key
      uses: nextbillion-ai/actions/gh-access-key@master
      with:
        nb-cicd-bot-pk: ${{ secrets.NB_CICD_BOT_PK }}

    - name: echo
      run: |
        #!/bin/bash
        set -e
        echo -------container----------
        echo "GH_ACCESS_KEY: $GH_ACCESS_KEY"
        if curl -H "Authorization: Bearer ${GH_ACCESS_KEY}" -H "Accept: application/vnd.github.v3+json"  https://api.github.com/repos/nextbillion-ai/tokamak | grep "Bad credentials" ; then
          echo "invalid access token"
          exit 1
        else
          echo "access token is working"
        fi
