name: gh-access-key-test
on:
  push:
    branches: ["master"]
    paths:
      - 'gh-access-key/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: chown
      run: |
        #!/bin/bash
        sudo chown -R $(whoami) .

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: get access key
      id: get_access_key
      uses: nextbillion-ai/actions/gh-access-key@master
      with:
        nb-cicd-bot-pk: ${{ secrets.NB_CICD_BOT_PK }}

    - name: echo
      run: |
        echo -------direct----------
        echo "GH_ACCESS_KEY: $GH_ACCESS_KEY"
        curl https://${GH_ACCESS_KEY}:x-oauth-basic@github.com/nextbillion-ai/tokamak/blob/main/README.md
  container-test:
    runs-on: self-hosted
    container:
      image: mwendler/jq

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: get access key
      id: get_access_key
      uses: nextbillion-ai/actions/gh-access-key@master
      with:
        nb-cicd-bot-pk: ${{ secrets.NB_CICD_BOT_PK }}

    - name: echo
      run: |
        echo -------container----------
        echo "GH_ACCESS_KEY: $GH_ACCESS_KEY"
        curl https://${GH_ACCESS_KEY}:x-oauth-basic@github.com/nextbillion-ai/tokamak/blob/main/README.md
