name: git-envs-test
on:
  pull_request:
    branches: ["master"]
    paths:
      - 'git-envs/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: chown
      run: |
        #!/bin/bash
        sudo chown -R $(whoami) .

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract Commit Info
      id: extract_commit_info
      uses: nextbillion-ai/actions/git-envs@${{ github.sha }}

    - name: Use Extracted Info
      run: |
        echo -------direct----------
        echo "Commit SHA: $CI_COMMIT_SHA"
        echo "Commit Author: $CI_COMMIT_AUTHOR"
        echo "Commit Tag: $CI_COMMIT_TAG"
  container-test:
    runs-on: self-hosted
    container:
      image: ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract Commit Info
      id: extract_commit_info
      uses: nextbillion-ai/actions/git-envs@${{ github.sha }}

    - name: Use Extracted Info
      run: |
        echo -------container----------
        echo "Commit SHA: $CI_COMMIT_SHA"
        echo "Commit Author: $CI_COMMIT_AUTHOR"
        echo "Commit Tag: $CI_COMMIT_TAG"
