name: CI Workflow

on:
  push:
    branches:
      - '*'  # Trigger the workflow on any branch push
    tags:
      - '*'  # Trigger the workflow on any tag push

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract Commit Info
      id: extract_commit_info
      uses: nextbillion-ai/actions/git-envs@master

    - name: Use Extracted Info
      run: |
        echo -------envs----------
        echo "Commit SHA: $CI_COMMIT_SHA"
        echo "Commit Author: $CI_COMMIT_AUTHOR"
        echo "Commit Tag: $CI_COMMIT_TAG"
